config:
  issuer: http://dex.auth.svc.cluster.local:5556

  storage:
    type: memory

  web:
    http: 0.0.0.0:5556

  enablePasswordDB: false

  staticClients:
    - id: oauth2-proxy
      name: "oauth2-proxy"
      secret: WEtFXLmTk5v7RUgMKGaoE6IBwj35c/3EReJc2dJnX7Q=
      redirectURIs:
        - http://laravel.local/oauth2/callback

  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23li732Qnk3366l1IN
        clientSecret: 7784baec4762d62220250e9c27f8ebce7c8b8209
        redirectURI: http://dex.auth.svc.cluster.local:5556/callback
        orgs:
          - name: maxiboole2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
