apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: kubequest
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: mysql:8
            env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            command:
            - /bin/sh
            - -c
            - |
              mkdir -p /backup
              mysqldump \
                -h mysql \
                -u laravel \
                laravel > /backup/backup-$(date +%F).sql
