apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    meta.helm.sh/release-name: crementation
    meta.helm.sh/release-namespace: crementation
  labels:
    app.kubernetes.io/instance: crementation
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crementation
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: crementation-0.1.0
  name: crementation
  namespace: crementation
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crementation
