apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: b859e69608a85173c529163c5970817b501653229032312fc2feae7a66480e26
      cni.projectcalico.org/podIP: 10.244.66.204/32
      cni.projectcalico.org/podIPs: 10.244.66.204/32
    creationTimestamp: "2026-06-13T00:19:27Z"
    generation: 1
    labels:
      run: vault-dev
    name: vault-dev
    namespace: vault
    resourceVersion: "917815"
    uid: 7c68873f-1069-4b58-b89a-e42d3d55e8cc
  spec:
    containers:
    - env:
      - name: VAULT_DEV_ROOT_TOKEN_ID
        value: root
      - name: VAULT_DEV_LISTEN_ADDRESS
        value: 0.0.0.0:8200
      image: hashicorp/vault:2.0.2
      imagePullPolicy: IfNotPresent
      name: vault-dev
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-hr6x9
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-10-2-49-174.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-hr6x9
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-16T17:29:29Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-13T00:19:27Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-16T17:29:29Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-16T17:29:29Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-13T00:19:27Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://119df8a9f6235068e65e46135005c2f1c62a87439d77f3afff3023908e56c236
      image: docker.io/hashicorp/vault:2.0.2
      imageID: docker.io/hashicorp/vault@sha256:3fd53308acccd9e4e83fde3e6c6cf5b15e0f7fac1ff7510780b8b23f5e4c3de7
      lastState:
        terminated:
          containerID: containerd://652648f7c9ad03d284a1aad87c49e26ae2461d3ef8532b7a8ab34b376de38fea
          exitCode: 255
          finishedAt: "2026-06-16T17:28:32Z"
          reason: Unknown
          startedAt: "2026-06-14T19:54:41Z"
      name: vault-dev
      ready: true
      resources: {}
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2026-06-16T17:29:29Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 100
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-hr6x9
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.2.49.174
    hostIPs:
    - ip: 10.2.49.174
    observedGeneration: 1
    phase: Running
    podIP: 10.244.66.204
    podIPs:
    - ip: 10.244.66.204
    qosClass: BestEffort
    startTime: "2026-06-13T00:19:27Z"
kind: List
metadata:
  resourceVersion: ""
