apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: ip-10-2-49-173.eu-central-1.compute.internal
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-06-13T17:47:00Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: mysql
    name: data-mysql-0
    namespace: kubequest
    resourceVersion: "588779"
    uid: a7c7588c-fb72-4116-9a74-6339a896b295
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-a7c7588c-fb72-4116-9a74-6339a896b295
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
