apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: laravel-db
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: laravel-db
    creationPolicy: Owner

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: secret
        property: DB_HOST

    - secretKey: DB_DATABASE
      remoteRef:
        key: secret
        property: DB_DATABASE

    - secretKey: DB_USERNAME
      remoteRef:
        key: secret
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret
        property: DB_PASSWORD
