deploymentMode: SingleBinary

loki:
  auth_enabled: false

singleBinary:
  replicas: 1

  nodeSelector:
    node-role.kubernetes.io/monitoring: monitoring

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    enabled: true
    storageClass: local-path
    size: 10Gi

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

gateway:
  enabled: false
